namespace Lantern.EQ.Animation
{
    public enum AnimationType
    {
        // Values < 74 match trilogy animation numbers and are used for spell data lookup
        None = 0,
        CombatKick = 1, // "c01"
        CombatPiercing = 2, // "c02"
        Combat2HSlash = 3, // "c03"
        Combat2HBlunt = 4, // "c04"
        Combat1HSlash = 5, // "c05"
        Combat1HSlashOffhand = 6, // "c06"
        CombatBash = 7, // "c07"
        CombatHandToHand = 8, // "c08"
        CombatArchery = 9, // "c09"
        CombatSwimAttack = 10, // "c10"
        CombatRoundKick = 11, // "c11"
        Damage1 = 12, // "d01"
        Damage2 = 13, // "d02"
        DamageTrap = 14, // "d03"
        DamageDrowningBurning = 15, // "d04"
        DamageDeath = 16, // "d05"
        LocomotionWalk = 17, // "l01"
        LocomotionRun = 18, // "l02"
        LocomotionJumpRun = 19, // "l03"
        LocomotionJumpStand = 20, // "l04"
        LocomotionFall = 21, // "l05"
        LocomotionDuckWalk = 22, // "l06"
        LocomotionClimb = 23, // "l07"
        Duck = 24, // "l08"
        LocomotionSwimTread = 25, // "l09"
        IdleStand = 26, // "o01"
        SocialCheer = 27, // "s01"
        SocialMourn = 28, // "s02"
        SocialWave = 29, // "s03"
        SocialRude = 30, // "s04"
        SocialYawn = 31, // "s05"
        PassiveStand = 32, // "p01"
        PassiveSitStand = 33, // "p02"
        PassiveRotating = 34, // "p03"
        // FIXME: Missing 35 "p04"
        Loot = 36, // "p05"
        LocomotionSwimMove = 37, // "p06"
        PassiveSitting = 38, // "p07"
        InstrumentDrum = 39, // "t01"
        InstrumentString = 40, // "t02"
        InstrumentWind = 41, // "t03"
        SpellCastDefense = 42, // "t04"
        SpellCastGeneral = 43, // "t05"
        SpellCastMissile = 44, // "t06"
        CombatFlyingKick = 45, // "t07"
        CombatRapidPunch = 46, // "t08"
        CombatHeavyPunch = 47, // "t09"
        SocialNod = 48, // "s06"
        SocialAmazed = 49, // "s07"
        SocialPlead = 50, // "s08"
        SocialClap = 51, // "s09"
        SocialDistress = 52, // "s10"
        SocialBlush = 53, // "s11"
        SocialChuckle = 54, // "s12"
        SocialBurp = 55, // "s13"
        SocialDuck = 56, // "s14"
        SocialLookAround = 57, // "s15"
        SocialDance = 58, // "s16"
        SocialBlink = 59, // "s17"
        SocialGlare = 60, // "s18"
        SocialDrool = 61, // "s19"
        SocialKneel = 62, // "s20"
        SocialLaugh = 63, // "s21"
        SocialPoint = 64, // "s22"
        SocialPonder = 65, // "s23"
        SocialReady = 66, // "s24"
        SocialSalute = 67, // "s25"
        SocialShiver = 68, // "s26"
        SocialTapFoot = 69, // "s27"
        SocialBow = 70, // "s28"
        PassiveStandArmsAtSides = 71, // "p08"
        IdleStandArmsAtSides = 72, // "o02"
        IdleSit = 73, // "o03"

        // Reverse animations
        LocomotionWalkReverse = 74,
        LocomotionRunReverse = 75,
        DuckReverse = 76,
        PassiveStandSit = 77,
        PassiveRotatingReverse = 78,
        LootReverse = 79,
    }
}
